version: '3'

services:
    mysql:
        image: mysql:8.0.17
        container_name: schedule_mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - ./docker/mysql:/var/lib/mysql
        env_file:
          - ./docker/mysql/env_dev
        ports:
            - "3306:3306"
    php:
        container_name: schedule_php
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/app
        ports:
            - "9003:9000"
        depends_on:
            - mysql
    nginx:
        image: nginx:stable
        container_name: schedule_nginx
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

